# -*- coding: utf-8 -*-
"""AVL CON TIEMPO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-qB36N_lTwAMkLMyPLOGC_kO62SZlc_i
"""

import java.util.*;

class AVLTree {
    class Node {
        int key, height;
        Node left, right;

        Node(int d) {
            key = d;
            height = 1;
        }
    }

    Node root;

    // Método para obtener la altura de un nodo
    int height(Node N) {
        return (N == null) ? 0 : N.height;
    }

    // Método para obtener el factor de equilibrio de un nodo
    int getBalance(Node N) {
        return (N == null) ? 0 : height(N.left) - height(N.right);
    }

    // Rotación a la derecha
    Node rightRotate(Node y) {
        Node x = y.left;
        Node T2 = x.right;

        x.right = y;
        y.left = T2;

        y.height = Math.max(height(y.left), height(y.right)) + 1;
        x.height = Math.max(height(x.left), height(x.right)) + 1;

        return x;
    }

    // Rotación a la izquierda
    Node leftRotate(Node x) {
        Node y = x.right;
        Node T2 = y.left;

        y.left = x;
        x.right = T2;

        x.height = Math.max(height(x.left), height(x.right)) + 1;
        y.height = Math.max(height(y.left), height(y.right)) + 1;

        return y;
    }

    // Inserción con manejo de claves duplicadas
    Node insert(Node node, int key) {
        if (node == null)
            return new Node(key);

        if (key < node.key)
            node.left = insert(node.left, key);
        else if (key > node.key)
            node.right = insert(node.right, key);
        else {
            // Clave duplicada: se permite y se inserta en el subárbol derecho
            node.right = insert(node.right, key);
        }

        node.height = 1 + Math.max(height(node.left), height(node.right));

        int balance = getBalance(node);

        // Rotaciones para balancear el árbol
        if (balance > 1 && key < node.left.key)
            return rightRotate(node);
        if (balance < -1 && key > node.right.key)
            return leftRotate(node);
        if (balance > 1 && key > node.left.key) {
            node.left = leftRotate(node.left);
            return rightRotate(node);
        }
        if (balance < -1 && key < node.right.key) {
            node.right = rightRotate(node.right);
            return leftRotate(node);
        }

        return node;
    }

    // Método para encontrar el nodo con el valor mínimo
    Node minValueNode(Node node) {
        Node current = node;
        while (current.left != null)
            current = current.left;
        return current;
    }

    // Eliminación de un nodo
    Node deleteNode(Node root, int key) {
        if (root == null)
            return root;

        if (key < root.key)
            root.left = deleteNode(root.left, key);
        else if (key > root.key)
            root.right = deleteNode(root.right, key);
        else {
            if ((root.left == null) || (root.right == null)) {
                Node temp = (root.left != null) ? root.left : root.right;
                if (temp == null) {
                    temp = root;
                    root = null;
                } else
                    root = temp;
                temp = null;
            } else {
                Node temp = minValueNode(root.right);
                root.key = temp.key;
                root.right = deleteNode(root.right, temp.key);
            }
        }

        if (root == null)
            return root;

        root.height = Math.max(height(root.left), height(root.right)) + 1;

        int balance = getBalance(root);

        // Rotaciones para balancear el árbol después de la eliminación
        if (balance > 1 && getBalance(root.left) >= 0)
            return rightRotate(root);
        if (balance > 1 && getBalance(root.left) < 0) {
            root.left = leftRotate(root.left);
            return rightRotate(root);
        }
        if (balance < -1 && getBalance(root.right) <= 0)
            return leftRotate(root);
        if (balance < -1 && getBalance(root.right) > 0) {
            root.right = rightRotate(root.right);
            return leftRotate(root);
        }

        return root;
    }

    // Recorrido en preorden (raíz, izquierda, derecha)
    void preOrder(Node node) {
        if (node != null) {
            System.out.print(node.key + " ");
            preOrder(node.left);
            preOrder(node.right);
        }
    }

    // Recorrido en inorden (izquierda, raíz, derecha)
    void inOrder(Node node) {
        if (node != null) {
            inOrder(node.left);
            System.out.print(node.key + " ");
            inOrder(node.right);
        }
    }

    // Recorrido en postorden (izquierda, derecha, raíz)
    void postOrder(Node node) {
        if (node != null) {
            postOrder(node.left);
            postOrder(node.right);
            System.out.print(node.key + " ");
        }
    }

    public static void main(String[] args) {
        AVLTree tree = new AVLTree();

        // Medir tiempo de inserción
        long startTime = System.nanoTime();
        tree.root = tree.insert(tree.root, 10);
        tree.root = tree.insert(tree.root, 20);
        tree.root = tree.insert(tree.root, 30);
        tree.root = tree.insert(tree.root, 40);
        tree.root = tree.insert(tree.root, 50);
        tree.root = tree.insert(tree.root, 25);
        long endTime = System.nanoTime();
        long insertionTime = endTime - startTime; // Tiempo en nanosegundos
        System.out.println("Tiempo de inserción: " + insertionTime + " ns");

        // Recorridos
        System.out.println("Recorrido preorden:");
        tree.preOrder(tree.root);
        System.out.println("\nRecorrido inorden:");
        tree.inOrder(tree.root);
        System.out.println("\nRecorrido postorden:");
        tree.postOrder(tree.root);

        // Medir tiempo de eliminación
        startTime = System.nanoTime();
        tree.root = tree.deleteNode(tree.root, 30);
        endTime = System.nanoTime();
        long deletionTime = endTime - startTime; // Tiempo en nanosegundos
        System.out.println("\nTiempo de eliminación: " + deletionTime + " ns");

        // Recorrido después de la eliminación
        System.out.println("Recorrido preorden después de eliminar 30:");
        tree.preOrder(tree.root);
    }
}